/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/ui/AppButton/index.vue')['default']
    AppHeader: typeof import('./src/components/ui/AppHeader.vue')['default']
    AppInput: typeof import('./src/components/ui/AppInput/index.vue')['default']
    AppPagination: typeof import('./src/components/ui/AppPagination/index.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton/index.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    ChartContainer: typeof import('./src/components/charts/ChartContainer.vue')['default']
    ChartTooltip: typeof import('./src/components/charts/ChartTooltip.vue')['default']
    Date: typeof import('./src/components/ui/Date.vue')['default']
    FileUpload: typeof import('./src/components/ui/AppInput/FileUpload.vue')['default']
    FilterTabs: typeof import('./src/components/FilterTabs.vue')['default']
    InvoiceFilters: typeof import('./src/components/invoices/InvoiceFilters.vue')['default']
    LinkButton: typeof import('./src/components/ui/LinkButton/index.vue')['default']
    MarketplaceChart: typeof import('./src/components/dashboard/MarketplaceChart.vue')['default']
    MeasuredInput: typeof import('./src/components/ui/AppInput/MeasuredInput.vue')['default']
    OrdersChart: typeof import('./src/components/charts/OrdersChart.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductCardSkeleton: typeof import('./src/components/ProductCardSkeleton.vue')['default']
    RevenueChart: typeof import('./src/components/charts/RevenueChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesChart: typeof import('./src/components/charts/SalesChart.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SettingsSidebar: typeof import('./src/components/settings/SettingsSidebar.vue')['default']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    TheBreadcrumbs: typeof import('./src/components/TheBreadcrumbs.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLayout: typeof import('./src/components/TheLayout.vue')['default']
    TheSidebar: typeof import('./src/components/ui/TheSidebar.vue')['default']
    TopProducts: typeof import('./src/components/dashboard/TopProducts.vue')['default']
    UIPanel: typeof import('./src/components/ui/UIPanel.vue')['default']
  }
}
