/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/invoices/': RouteRecordInfo<'/invoices/', '/invoices', Record<never, never>, Record<never, never>>,
    '/invoices/[id]/': RouteRecordInfo<'/invoices/[id]/', '/invoices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/orders/': RouteRecordInfo<'/orders/', '/orders', Record<never, never>, Record<never, never>>,
    '/orders/[id]': RouteRecordInfo<'/orders/[id]', '/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/': RouteRecordInfo<'/orders/[id]/', '/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/[productId]/': RouteRecordInfo<'/products/[productId]/', '/products/:productId', { productId: ParamValue<true> }, { productId: ParamValue<false> }>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    'settings-api': RouteRecordInfo<'settings-api', '/settings/api', Record<never, never>, Record<never, never>>,
    'settings-password': RouteRecordInfo<'settings-password', '/settings/password', Record<never, never>, Record<never, never>>,
    'settings-profile': RouteRecordInfo<'settings-profile', '/settings/profile', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]/': RouteRecordInfo<'/users/[id]/', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/warehouses/': RouteRecordInfo<'/warehouses/', '/warehouses', Record<never, never>, Record<never, never>>,
  }
}
