import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetUno,
} from "unocss";
import { FileSystemIconLoader } from "unplugin-icons/dist/loaders.js";

export default defineConfig({
  shortcuts: {
    "heading-1": "text-h1 font-bold",
    "heading-2": "text-h2 font-bold",
    "heading-3": "text-h3 font-bold",
    "heading-4": "text-h4 font-bold",
    "heading-5": "text-h5 font-bold",
    "heading-6": "text-h6 font-bold",
    "body-xlarge-regular": "text-body-xlarge font-regular",
    "body-xlarge-medium": "text-body-xlarge font-medium",
    "body-xlarge-semibold": "text-body-xlarge font-semibold",
    "body-xlarge-bold": "text-body-xlarge font-bold",
    "body-large-regular": "text-body-large font-regular",
    "body-large-medium": "text-body-large font-medium",
    "body-large-semibold": "text-body-large font-semibold",
    "body-large-bold": "text-body-large font-bold",
  },
  theme: {
    animation: {
      keyframes: {
        "bounce-rotate": "{from {transform: scale(1) rotate(0deg)} 50% {transform: scale(0.9) rotate(-3deg)} to {transform: scale(1) rotate(0deg)}}",
      },
      durations: {
        "bounce-rotate": "0.3s",
      },
      timingFns: {
        "bounce-rotate": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
    fontSize: {
      h1: ["48px", "160%"],
      h2: ["40px", "160%"],
      h3: ["32px", "160%"],
      h4: ["24px", "160%"],
      h5: ["20px", "160%"],
      h6: ["18px", "160%"],
    },
    fontFamily: {
      sans: "Gilroy",
      gilroy: "Gilroy",
    },
    colors: {
      "main": "#EA6001",
      "second": "#0A2635",
      "background": "#F4F4F4",
      "white": "#FFFFFF",
      "black": "#000000",
      "grey": "#ABACAE",
      "green": "#77BD8B",
      "red": "#FF6E4E",
      "blue": "#00A9F1",
      "other-deep-purple": "#673AB3",
      "other-blur": "#1A96F0",
      "other-green": "#4AAF57",
      "other-red": "#F54336",
      "other-brown": "#7A5548",
      "other-yellow": "#FFEB4F",
      "other-orange": "#FF981F",
      "info": "#48CFAF",
      "grayscale": {
        50: "#FAFAFA",
        100: "#F5F5F5",
        200: "#EEEEEE",
        300: "#E0E0E0",
        400: "#BDBDBD",
        800: "#424242",
      },
    },
  },
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
      prefix: "i-",
      collections: {
        jq: FileSystemIconLoader(
          "./assets/icons/",
        ),
      },
      extraProperties: {
        "display": "inline-block",
        "vertical-align": "middle",
      },
    }),
  ],
  safelist: [
    "i-jq-category-filled",
    "i-jq-card-box-filled",
    "i-jq-car-delivery",
    "i-jq-tick",
    "i-jq-close",
    "i-jq-check",
    "i-jq-arrow-right",
    "i-jq-arrow-left",
    "i-jq-arrow-up",
    "i-jq-arrow-down",
    "i-jq-search",
    "i-jq-filter",
    "i-jq-sort",
    "i-jq-edit",
    "i-jq-download",
    "i-jq-upload",
    "i-jq-upload-filled",
    "i-jq-upload-outlined",
    "i-jq-download",
    "i-jq-download-filled",
    "i-jq-download-outlined",
    "i-jq-trash",
  ],
});
